- name: Check response of localhost web server on port 443
  uri:
    url: https://localhost:443
    validate_certs: no
    return_content: no
  register: result
  tags:
    - web-server

- name: Print response status code
  debug:
    msg: "Response status code: {{ result.status }}"
  tags:
    - web-server

- name: Retrieve SSL certificate details
  shell: "echo | openssl s_client -connect localhost:443 2>/dev/null | openssl x509 -noout -dates -subject"
  register: cert_info
  tags:
    - web-server

- name: Display raw certificate information
  debug:
    var: cert_info.stdout
  tags:
    - web-server