all:
  vars:
    ansible_user: root
  children:
    deploy:
      hosts:
        test.example.com:
          ansible_host: 10.0.0.1
        dev.example.com:
          ansible_host: 10.0.0.2
        prod.example.com:
          ansible_host: 10.0.0.3
